#!/bin/bash

if ! command -v gpg > /dev/null 2>&1
then
    echo "GPG nicht installiert."
    exit 1
fi

if [ $# -eq 0 ]
  then
    echo "Keine Maliadresse übergeben"
    exit 1
fi

wkdhash=$(gpg --with-wkd-hash --list-public-keys "$1" | sed "4q;d" | tr -d ' ' | awk '{print substr($0,0,31)}')
gpg --no-armor --export "$1" > "$wkdhash"